# Generated by Django 4.2.3 on 2023-07-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveBigIntegerField(),
        ),
    ]
