# Generated by Django 4.2.3 on 2023-07-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0002_student_gender_alter_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
