# Generated by Django 4.2.3 on 2023-07-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0003_remove_student_address_remove_student_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=2),
        ),
    ]
